name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install terser -g

      - name: Run mypy
        run: |
          mypy .

      - name: Run Pytest
        run: |
          ./test.sh

      - name: Import
        run: |
          ./importer.py test-data/*.json

      - name: Generate
        run: |
          ./generator.py
